version: '3'
services:
    chico_planner:
      container_name: react
      build: ./chico-planner
      volumes:
        - ./chico_planner/:/usr/src/app/
      ports:
        - '3000:3000'
      command: [ "npm", "start" ]
